import 'dotenv/config';
import { db } from '../src/db';
import { bikesTable } from '../src/db/schema';

async function seed() {
  try {
    console.log('🌱 Seeding database...');

    // Datos de ejemplo de motos en Palma de Mallorca (lugares emblemáticos)
    const bikes = [
      // Catedral de Santa María de Palma (La Seu)
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5672',
        longitude: '2.6536',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Castillo de Bellver
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5656',
        longitude: '2.6253',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Baños Árabes
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5731',
        longitude: '2.6535',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Parque del Mar
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5665',
        longitude: '2.6530',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Plaza de España
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5744',
        longitude: '2.6537',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Paseo Marítimo
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5680',
        longitude: '2.6480',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Playa de Palma
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5200',
        longitude: '2.7000',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Puerto de Palma
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5700',
        longitude: '2.6400',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Mercado del Olivar
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5715',
        longitude: '2.6510',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Calle Jaime III
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5720',
        longitude: '2.6520',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Plaça Major
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5725',
        longitude: '2.6530',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Avenida de Jaume III
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5730',
        longitude: '2.6540',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Es Baluard (Museo de Arte Contemporáneo)
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5685',
        longitude: '2.6475',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Cala Major
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5400',
        longitude: '2.6200',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // Aeropuerto de Palma (zona cercana)
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5500',
        longitude: '2.7300',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // ========== 10 MOTOS EN SANT JOSEP OBRER (distribución aleatoria) ==========
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5812',
        longitude: '2.6458',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5837',
        longitude: '2.6483',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5824',
        longitude: '2.6512',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5841',
        longitude: '2.6467',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5808',
        longitude: '2.6495',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5833',
        longitude: '2.6521',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5819',
        longitude: '2.6474',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5846',
        longitude: '2.6503',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5827',
        longitude: '2.6489',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5839',
        longitude: '2.6518',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // ========== 5 MOTOS CERCA DE COMETALABS (distribución aleatoria) ==========
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5753',
        longitude: '2.6557',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5768',
        longitude: '2.6564',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5759',
        longitude: '2.6572',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5764',
        longitude: '2.6559',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5772',
        longitude: '2.6568',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      // ========== 45 MOTOS DISTRIBUIDAS ALEATORIAMENTE POR PALMA ==========
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5718',
        longitude: '2.6527',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5692',
        longitude: '2.6541',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5747',
        longitude: '2.6515',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5683',
        longitude: '2.6492',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5729',
        longitude: '2.6538',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5707',
        longitude: '2.6506',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5736',
        longitude: '2.6523',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5698',
        longitude: '2.6519',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5714',
        longitude: '2.6545',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5687',
        longitude: '2.6486',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5751',
        longitude: '2.6532',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5703',
        longitude: '2.6498',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5726',
        longitude: '2.6511',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5742',
        longitude: '2.6549',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5695',
        longitude: '2.6503',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5711',
        longitude: '2.6528',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5733',
        longitude: '2.6517',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5689',
        longitude: '2.6495',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5756',
        longitude: '2.6535',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5705',
        longitude: '2.6512',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5722',
        longitude: '2.6542',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5745',
        longitude: '2.6508',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5691',
        longitude: '2.6489',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5717',
        longitude: '2.6531',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5738',
        longitude: '2.6526',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5685',
        longitude: '2.6501',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5754',
        longitude: '2.6543',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5709',
        longitude: '2.6494',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5724',
        longitude: '2.6518',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5741',
        longitude: '2.6534',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5697',
        longitude: '2.6507',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5713',
        longitude: '2.6524',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5735',
        longitude: '2.6513',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5681',
        longitude: '2.6497',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5758',
        longitude: '2.6540',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5701',
        longitude: '2.6515',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5720',
        longitude: '2.6537',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5743',
        longitude: '2.6505',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5693',
        longitude: '2.6491',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5715',
        longitude: '2.6521',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5731',
        longitude: '2.6519',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5688',
        longitude: '2.6504',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5752',
        longitude: '2.6536',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5706',
        longitude: '2.6493',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5723',
        longitude: '2.6544',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5746',
        longitude: '2.6510',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5694',
        longitude: '2.6509',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5716',
        longitude: '2.6525',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5734',
        longitude: '2.6520',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5682',
        longitude: '2.6496',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5757',
        longitude: '2.6539',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5704',
        longitude: '2.6516',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5721',
        longitude: '2.6533',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5744',
        longitude: '2.6507',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5696',
        longitude: '2.6502',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5712',
        longitude: '2.6522',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5732',
        longitude: '2.6514',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5686',
        longitude: '2.6498',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5755',
        longitude: '2.6537',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5708',
        longitude: '2.6510',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5725',
        longitude: '2.6546',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5748',
        longitude: '2.6509',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5699',
        longitude: '2.6500',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5710',
        longitude: '2.6526',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5737',
        longitude: '2.6529',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5684',
        longitude: '2.6490',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5750',
        longitude: '2.6538',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5702',
        longitude: '2.6513',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5727',
        longitude: '2.6530',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5749',
        longitude: '2.6511',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5690',
        longitude: '2.6505',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5719',
        longitude: '2.6527',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5739',
        longitude: '2.6524',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5680',
        longitude: '2.6499',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
      {
        status: 'AVAILABLE' as const,
        latitude: '39.5740',
        longitude: '2.6530',
        reservedUntil: null,
        reservedBy: null,
        rideStartedAt: null,
      },
    ];

    // Insertar motos
    const insertedBikes = await db.insert(bikesTable).values(bikes).returning();

    console.log(`✅ Inserted ${insertedBikes.length} bikes`);
    console.log('Bike IDs:', insertedBikes.map((b) => b.id).join(', '));
    console.log('🎉 Seeding completed!');
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  }
}

seed()
  .then(() => {
    console.log('✨ Seed script finished');
    process.exit(0);
  })
  .catch((error) => {
    console.error('💥 Seed script failed:', error);
    process.exit(1);
  });

